### ISSUE TITLE
Hide Packages & Releases

### ISSUE THREAD

**Issue by verma-kunal** [akshitadixit/RAKSHA#17]
Suggested to hide packages and releases if not being used in the project/repo.

![Screenshot 2021-07-12 at 10 28 44 AM](https://user-images.githubusercontent.com/72245772/125233332-f0d39980-e2fb-11eb-907e-b8f2d8438ad7.png)

**Comment by akshitadixit** [comment]
I remember this from one of Eddie's sessions. Thanks for pointing out :)
