### ISSUE TITLE
Update About Section

### ISSUE THREAD

**Issue by verma-kunal** [akshitadixit/RAKSHA#18]
Suggested to update the about section with the following:

- Adding a small description about the project
- Giving a link to the deployed version, or hosted on GH pages
- adding relevant tags related to the project

![Screenshot 2021-07-12 at 10 31 58 AM](https://user-images.githubusercontent.com/72245772/125233534-6475a680-e2fc-11eb-9ac6-be2bf97ccbe0.png)

**Comment by akshitadixit** [comment]
Thanks for the issue Kunal! I almost skipped this.
